# -*- coding: utf-8 -*-
"""dataCollec.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eKzMvNMALs_ksVMmPJenRjIF1OWnfx2q
"""

import requests
import pandas as pd

def fetch_data(api_url):
    response = requests.get(api_url)
    if response.status_code == 200:
        return response.json().get("markets", [])
    else:
        print("Failed to fetch data from API")
        return []

def create_dataframe(data):
    if not data or not isinstance(data, list):
        print("Invalid data format or missing data")
        return None

    columns = ["Date", "Index_Code", "Index_Name", "Daily_Index", "Previous_Close", "Daily_Variation", "Highest_Index", "Lowest_Index", "Opening_Index"]
    rows = []

    for entry in data:
        date = entry.get("arabSeance", "")
        index_code = entry.get("referentiel", {}).get("ticker", "")
        index_name = entry.get("referentiel", {}).get("stockName", "")
        daily_index = entry.get("close", 0)
        previous_close = entry.get("last", 0)
        daily_variation = entry.get("change", 0)
        highest_index = entry.get("high", 0)
        lowest_index = entry.get("low", 0)
        opening_index = entry.get("open", 0)

        rows.append([date, index_code, index_name, daily_index, previous_close, daily_variation, highest_index, lowest_index, opening_index])

    df = pd.DataFrame(rows, columns=columns)
    return df

def main():
    api_url = "https://bvmt.com.tn/rest_api/rest/market/groups/11,12,52,95,99"
    data = fetch_data(api_url)
    if data:
        df = create_dataframe(data)
        print(df.head())

if __name__ == "__main__":
    main()

api_url = "https://www.ilboursa.com/marches/actualites_bourse_tunis"